% run this file to build getOPERATORS();

mex -output getOPERATORS -L"/Users/georgyguryev/Documents/mri_cpp/marie/c++/libs/" -lmc01mlaa -lmc01utils -lmc01vie -lmc01geo -lmc01quads...
    -I"/Users/georgyguryev/Documents/mri_cpp/marie/c++/include/" ...
    -I"/Users/georgyguryev/Documents/mri_cpp/marie/c++/external/boost_1_58_0c/" vie_operator_mex.cpp 